defaults: &defaults
  host: localhost
  autocreate_indexes: false
  allow_dynamic_fields: false
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3

development:
  <<: *defaults
  database: chromada_development

test:
  <<: *defaults
  database: chromada_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: flame.mongohq.com
  port: 27036
  username: root
  password: root
  database: chromada
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>