- employees:
    - create
    - delete
    - view:
        - firstname
        - lastname
    - edit:
        - firstname
        - lastname
        
- roles:
    - create
    - delete
    - edit
    
- users:
    - create
    - delete