# CRUD (modified for human)
# Create: create, new
# Delete: destroy
# View: index, show
# Edit: edit, update

# assuming a starting point of company entity
- edit
- billing

- employees:
    - create
    - delete
    - view
    - edit
        
- permissions:
    - create
    - delete
    - view
    - edit
    
- users:
    - create
    - delete
    - view
    - edit