# CRUD (modified for human)
# Create: create, new
# Delete: destroy
# View: index, show
# Edit: edit, update

- employees:
    - create
    - delete
    - view
    - edit
        
- roles:
    - create
    - delete
    - view
    - edit
